title: MSVC Gallery with Face Matching
description: 3 Semesterarbeit für Cloud Native Engineer Studium
theme: just-the-docs

url: https://noluchs.github.io/MSCV-Gallery-with-Face-Matching/

aux_links:
   Projektplanung: https://github.com/users/noluchs/projects/6
