version: '3.9'

name: face-recognition-gallery-prod

networks:
  eventgallery-net:

services:
  proxy:
    container_name: proxy
    restart: unless-stopped
    image: jonasal/nginx-certbot:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - CERTBOT_EMAIL=noah.luchsinger@outlook.com
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    networks:
      - eventgallery-net


  eventgallery-frontend:
    #image: ghcr.io/noluchs/mscv-gallery-with-face-matching/msvcfrontend:latest
    build:
      context: ./frontend
      dockerfile: 'Dockerfile.prod'
    container_name: eventgallery-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-frontend

  eventgallery-backend:
    #image: ghcr.io/noluchs/mscv-gallery-with-face-matching/msvcbackend:latest
    build:
      context: ./backend
      dockerfile: 'Dockerfile.prod'
    container_name: eventgallery-backend
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .env
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-backend
    depends_on:
      eventgallery-db:
        condition: service_healthy

  eventgallery-db:
    image: mysql:5.7
    container_name: eventgallery-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventgallery
    networks:
      - eventgallery-net
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - eventgallery-db:/var/lib/mysql

volumes:
  eventgallery-db:
  nginx_secrets: