version: '3.9'

name: face-recognition-gallery-prod

networks:
  eventgallery-net:

services:
  traefik:
    image: traefik:v3.0.4
    container_name: traefik
    networks:
      eventgallery-net:
        aliases:
          - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/traefik.prod.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`gallery.luchsphoto.ch`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$H6uskkkW$$IgXLP6rZW.UeGyQh77lxY0"




  eventgallery-frontend:
    #image: ghcr.io/noluchs/mscv-gallery-with-face-matching/msvcfrontend:latest
    build:
      context: ./frontend
      dockerfile: 'Dockerfile.prod'
    container_name: eventgallery-frontend
    restart: always
    ports:
      - 3000:3000
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gallery.luchsphoto.ch`) && Path(`/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"



  eventgallery-backend:
    #image: ghcr.io/noluchs/mscv-gallery-with-face-matching/msvcbackend:latest
    build:
      context: ./backend
      dockerfile: 'Dockerfile.prod'
    container_name: eventgallery-backend
    ports:
      - 5000:5000
    restart: always
    env_file:
      - .env
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-backend
    depends_on:
      eventgallery-db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`gallery.luchsphoto.ch`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"


  eventgallery-db:
    image: mysql:5.7
    container_name: eventgallery-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventgallery
    networks:
      - eventgallery-net
    healthcheck:
      test: mysqladmin ping -h localhost -uroot --password=$$MYSQL_ROOT_PASSWORD
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - eventgallery-db:/var/lib/mysql

volumes:
  eventgallery-db:
  nginx_secrets: