version: '3.9'

name: face-recognition-gallery

networks:
  eventgallery-net:

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    container_name: frontend-dev
    networks:
       eventgallery-net:
        aliases:
          - eventgallery-frontend
    environment:
      - CHOKIDAR_USEPOLLING=true



  eventgallery-backend:
    container_name: eventgallery-backend-dev
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-backend
    restart: always
    ports:
      - "5001:5000"
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - environment.env
    depends_on:
      eventgallery-db:
        condition: service_healthy

  eventgallery-db:
    image: mysql:latest
    container_name: eventgallery-db-backend-dev
    networks:
      eventgallery-net:
        aliases:
          - eventgallery-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: eventgallery
      MYSQL_PASSWORD: zHa3eXfvof6Z2nX
      MYSQL_DATABASE: eventgallery
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "--password=$$MYSQL_ROOT_PASSWORD"]
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - eventgallery-db:/var/lib/mysql

volumes:
  eventgallery-db: